apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-config
  namespace: healthcare-service
data:
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "healthdb"
