apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  namespace: healthcare-service
  labels:
    app: healthcare-service
spec:
  type: ClusterIP
  selector:
    app: healthcare-service
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  sessionAffinity: None
